### ISSUE TITLE
Mod not working 

### ISSUE THREAD

**Issue by VictorRoyal20** [saefulbarkah/MAUNG-MOD#1]
after launch mod nothing happens, in game i not receive the message "MAUNG MOD LOADED"

**Comment by saefulbarkah** [comment]
![Screenshot (86)](https://github.com/user-attachments/assets/4ebfbb7f-767a-4f48-b6b3-35a6bd62b53a)

Still working, try open menu ALT + X

**Comment by VictorRoyal20** [comment]
![image](https://github.com/user-attachments/assets/f00dbdd4-75fb-4099-b45a-b8c91c6ba852)
wuthering waves? no wuthering waves game?

**Comment by VictorRoyal20** [comment]
now mod open, but menu dosen't

**Comment by VictorRoyal20** [comment]
done

**Comment by VictorRoyal20** [comment]
thx so much, i have another question, mod is detected?

**Comment by VictorRoyal20** [comment]
last question

**Comment by saefulbarkah** [comment]
> thx so much, i have another question, mod is detected?

No, but bannable yes because you're cheating

**Comment by VictorRoyal20** [comment]
> > thx so much, i have another question, mod is detected?
> 
> No, but bannable? yes because you're cheating

okay, thx so much
